title: My GitHub Pages Site # Sets the title of your website
description: A simple example for GitHub Pages # Sets a short description of your site
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
